apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-ddos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy-ddos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpTargetPort }}
    nodePort: {{ .Values.service.httpNodePort }}
    protocol: TCP
  - name: admin
    port: {{ .Values.service.adminPort }}
    targetPort: {{ .Values.service.adminTargetPort }}
    nodePort: {{ .Values.service.adminNodePort }}
    protocol: TCP
  selector:
    {{- include "envoy-ddos.selectorLabels" . | nindent 4 }}
